version: "3"

# Development environment override
services:
  backend:
    build:
      context: backend
      target: php_dev
    volumes:
      - ./backend:/srv/app
      - ./backend/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"

  caddy:
    command: [ "caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--watch" ]
    build:
      context: backend
      target: caddy_base
    volumes:
      - ./backend/public:/srv/app/public:ro
      - ./backend/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
